### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by mcollina** [nearform/the-fastify-workshop#305]
I run `npm start` and I'm getting:

```
2:10:28 PM [vite] Internal server error: EMFILE: too many open files, open '/Users/matteo/repositories/the-fastify-workshop/src/step-2/node_modules/@babel/generator/node_modules/source-map/README.md'
   (x3)
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: EMFILE: too many open files, open '/Users/matteo/repositories/the-fastify-workshop/components.d.ts'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/Users/matteo/repositories/the-fastify-workshop/components.d.ts'
}
```

I don't know what is the problem.

**Comment by galvez** [comment]
I'm trying it now. Hang in there.

**Comment by galvez** [comment]
Weird, boots for me after a clean `npm i` and `npm start`:

<img width="1078" alt="Screen Shot 2022-02-22 at 10 17 19" src="https://user-images.githubusercontent.com/12291/155140046-5a5169bf-9f92-45b7-a894-94afbd4a2e71.png">

Seems to generate a `components.d.ts` file — not sure what that's used for.

**Comment by sameer-coder** [comment]
I am investigating this too. I think it might be a problem with the file watcher that runs the presentation

**Comment by galvez** [comment]
Re: components.d.ts, it's harmless, it's just for autocompletion in VSCode for the built-in components. It's auto generated and should be pushed to the repository. The origina Vite configuration can be overridden and this can be disabled, but I see no point in doing it.

**Comment by mcollina** [comment]
What's your ulimit?

**Comment by sameer-coder** [comment]
I am on windows so I guess your ulimit must be different than mine since you are on mac. I have pushed a PR to fix the `npm run build` command. Maybe you could try to run `npm run build` and then just run the presentation using something like a `local-web-server`. I can add a command for that too if you would like.

**Comment by galvez** [comment]
Interesting:

```sh
> % ulimit
unlimited
```

**Comment by mcollina** [comment]
`unlimit -n`

**Comment by mcollina** [comment]
```

$ npm run build

> the-fastify-workshop@1.0.0 build /Users/matteo/repositories/the-fastify-workshop
> slidev build



  ●■▲
  Slidev  v0.28.7

  theme   slidev-theme-nearform
  entry   /Users/matteo/repositories/the-fastify-workshop/slides.md


vite v2.8.4 building for production...
<script src="/Users/matteo/repositories/the-fastify-workshop/node_modules/@nearform/nf-present/assets/remark-latest.min.js"> in "/index.html" can't be bundled without type="module" attribute
✓ 2 modules transformed.
[vite]: Rollup failed to resolve import "/Users/matteo/repositories/the-fastify-workshop/node_modules/@nearform/nf-present/assets/styles.css" from "index.html".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "/Users/matteo/repositories/the-fastify-workshop/node_modules/@nearform/nf-present/assets/styles.css" from "index.html".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/Users/matteo/repositories/the-fastify-workshop/node_modules/vite/dist/node/chunks/dep-971d9e33.js:39226:19)
    at onwarn (/Users/matteo/repositories/the-fastify-workshop/node_modules/vite/dist/node/chunks/dep-971d9e33.js:39004:13)
    at Object.onwarn (/Users/matteo/repositories/the-fastify-workshop/node_modules/rollup/dist/shared/rollup.js:23118:13)
    at ModuleLoader.handleResolveId (/Users/matteo/repositories/the-fastify-workshop/node_modules/rollup/dist/shared/rollup.js:22392:26)
    at /Users/matteo/repositories/the-fastify-workshop/node_modules/rollup/dist/shared/rollup.js:22353:26 {
  watchFiles: [
    '/Users/matteo/repositories/the-fastify-workshop/index.html',
    'vite/modulepreload-polyfill',
    '/Users/matteo/repositories/the-fastify-workshop/styles.css',
    '/Users/matteo/repositories/the-fastify-workshop/node_modules/@slidev/client/main.ts'
  ]
}
[!] Error: unfinished hook action(s) on exit:
(vite:css) transform "/Users/matteo/repositories/the-fastify-workshop/styles.css"
(vite:esbuild) transform "/Users/matteo/repositories/the-fastify-workshop/node_modules/@slidev/client/main.ts"

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! the-fastify-workshop@1.0.0 build: `slidev build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the the-fastify-workshop@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matteo/.npm/_logs/2022-02-22T14_11_40_769Z-debug.log

```

**Comment by mcollina** [comment]
a nice `rm -rf the-fastify-workshop` fixed it.
